import type { Metadata } from "next";
import "./globals.css";
import { HeroUIProviders } from "@/provider/HeroUIProviders";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <HeroUIProviders>
          <div className="fixed inset-0 bg-bgPrimary"> </div>
          <div className="relative z-10">{children}</div>
        </HeroUIProviders>
      </body>
    </html>
  );
}
